### ISSUE TITLE
JAX-RS resources resolution should be targeted towards Spring beans only

### ISSUE THREAD

**Issue by fabiocarvalho777** [paypal/resteasy-spring-boot#19]
JAX-RS resources resolution should be targeted towards Spring beans only, instead of any regular (non-Spring bean) JAX-RS Path or Provider annotated class. That means it is necessary to move from classpath scanning to Spring beans scanning when looking for JAX-RS resources and providers.

**Comment by rgrebski** [comment]
Has that been fixed ? I can steel see classpath scanning in 2.0.1-RELEASE

**Comment by fabiocarvalho777** [comment]
One more thing. I have just opened this [new feature request here](https://github.com/paypal/resteasy-spring-boot/issues/22). Is that something you are looking for?

**Comment by rgrebski** [comment]
Thx, this is exactly what I am looking for.
If you need help, let me know, I would be happy to contribute.

**Comment by fabiocarvalho777** [comment]
Thanks Radek!! I am going to work on it today and release a new version with it. I will let you know when it is ready.

**Comment by fabiocarvalho777** [comment]
Hey Radek, issue #22 has been finished. It is already available via version 2.1.0-SNAPSHOT. Read [this section](https://github.com/paypal/resteasy-spring-boot/tree/2.1.x#registering-jax-rs-application-classes) to know how to use. I am going to work on one or more issue and then release version 2.1.0, hopefully that will be done by the end of this week. Let me know if you have any question or comment.

**Comment by fabiocarvalho777** [comment]
@rgrebski version 2.1.0 has just been released, and it contains #22

**Comment by rgrebski** [comment]
Thanks a lot ! Im gonna use it next week once Im back from holiday!

**Comment by rgrebski** [comment]
Thanks again, works like a charm. Before the fix when I tried running from .jar (java -jar my-spring-boot-app.jar) it could not find RestEasy Application class, but now I registered it as a Spring bean and works just perfect
