### ISSUE TITLE
Spring 4.1 is not supported although it easily can be

### ISSUE THREAD

**Issue by janzak** [paypal/resteasy-spring-boot#40]
Compatibility of resteasy-spring-boot with Spring 4.1 is unfortunately broken just because of using the Import annotation to directly reference a Spring component which is not allowed in this version of Spring. The limitation has been removed in Spring 4.2 but I would like to use resteasy-spring-boot in a project where I have to keep Spring 4.1 for certain reasons.

However, the Import annotation in the ResteasySpringBootConfig class can be easily replaced by the Beans annotations which is an approach that not only enables me to use Spring 4.1 but also is - at least from my perspective - more straightforward.

**Comment by janzak** [comment]
Please, see https://github.com/paypal/resteasy-spring-boot/pull/41

**Comment by fabiocarvalho777** [comment]
Hi Janzak.

In your PR you forgot to remove the @Component from one those two classes. Please, go ahead and fix that in your PR (squash your second commit please).

Notice also that the CI build for your PR failed. Would you mind checking that too? I can't merge it if the CI build doesn't pass.

Finally, I need to say that this project was reviewed by Spring and Spring Boot framework teams and using that @Import annotation was actually something they recommended.

Anyways, having said all of that, please take care of the issues I mentioned, and let me think about this case a little better and then I will respond. But thanks a lot for reaching me, your feedback and your PR.

**Comment by fabiocarvalho777** [comment]
Merged. This change will be part of the next release (whose deliver date has not been decided yet). Thanks for you contribution.

**Comment by fabiocarvalho777** [comment]
I will leave this open to remind me to add it to the next release release notes document.

**Comment by fabiocarvalho777** [comment]
Closing and releasing it today.

**Comment by fabiocarvalho777** [comment]
Version 2.2.1-RELEASE has just been published with your changes.
