### ISSUE TITLE
Fix CI travis jpm usage

### ISSUE THREAD

**Issue by fabiocarvalho777** [paypal/resteasy-spring-boot#44]
After that is solved, remove comment mark from Travis CI badge in README.md

**Comment by fehmer** [comment]
Hi @fabiocarvalho777 ,

PR #48 fixes the travis build. I updated the installation of jpm according to the documentation. I tried to create the needed directories within the travis script to avoid using sudo on the jpm calls but i had no luck. If you are okay with using sudo the PR should fix the travis problem.

best regards, christian

**Comment by fabiocarvalho777** [comment]
Hello @fehmer . Thanks for all your help. I will review and merge your PR and everything else after January 11th, as I am on vacation now. Thanks again!

**Comment by fabiocarvalho777** [comment]
@fehmer your PR has been merged, and it worked. The only pending issue now is the Travis CI badge in the README document that, for some reason, even though the latest build succeeded, showed as "error". But I consider that a separated issue, since the actual build is for sure working. I wait a little to see if that might be a synchronization issue anyhow. If not, I will open a separated issue for that.

Thanks again!

**Comment by fabiocarvalho777** [comment]
Just fixed the Travis CI badge by cherry picking your fix to master branch, so it is all good now. Thanks again!
