### ISSUE TITLE
Warning messages during startup

### ISSUE THREAD

**Issue by sergeykad** [paypal/resteasy-spring-boot#56]
Spring reports the following warnings on Startup:

WARN  o.s.c.a.ConfigurationClassEnhancer - @Bean method ResteasySpringBootConfig.springBeanProcessor is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.
WARN  o.s.c.a.ConfigurationClassEnhancer - @Bean method ResteasySpringBootConfig.resteasyEmbeddedServletInitializer is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.

**Comment by fabiocarvalho777** [comment]
Thanks for reporting it. I will get that fixed and release a new version with the fix very soon.

**Comment by fabiocarvalho777** [comment]
RESTEasy Spring Boot starter version 2.3.0 has just been released with this fix. Notice that it also has RESTEasy and Spring Boot revved up to their latest release versions.

**Comment by fabiocarvalho777** [comment]
By the way, it takes some time before Maven public release repositories synchronize, so give it some time before trying to use version 2.3.0. Usually it doesn't take more than one day.
