### ISSUE TITLE
JAX-RS application and endpoints don't get registered when running mvn spring-boot:run

### ISSUE THREAD

**Issue by fabiocarvalho777** [paypal/resteasy-spring-boot#6]
When starting the application from the IDE, or from a java command directly, the application starts-up fine and everything works as expected.

However, if the application is started using the **mvn spring-boot:run** command, then for some reason the JAX-RS application and endpoints don't get registered.

The following log statements are missing when running the sample application from **mvn spring-boot:run** command.

```
2016-03-28 09:21:04.299  INFO 67757 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'com.test.JaxrsApplication' to [/sample-app/*]
2016-03-28 09:21:04.729  INFO 67757 --- [           main] org.jboss.resteasy.resteasy_jaxrs.i18n   : RESTEASY002225: Deploying javax.ws.rs.core.Application: class com.test.JaxrsApplication
```

**Comment by sgardnerdell** [comment]
I've done some debugging of this issue and have tracked the problem down to the ResteasyEmbeddedServletInitializer::findJaxrsClasses method.

When instantiating the Reflections API, this method uses ClasspathHelper.forJavaClassPath().
This gives the correct results when running the application directly, but when running the mvn spring-boot:run command this only returns a single entry (a jar from the maven runtime).

Changing this to use ClasspathHelper.forClassLoader() fixes the issue, however this method returns additional entries (for JRE jar files) so this will reduce the efficiency of the reflections scanner.  Probably not a huge problem though, especially as this is only run at startup.

**Comment by fabiocarvalho777** [comment]
Thanks. The solution you mention breaks the application when building and running from the IDE. I have written a solution that works in all situations. I am checking in the change. Thanks again for reporting it!!

**Comment by sgardnerdell** [comment]
Interesting.  It worked from the IDE in my environment.  Just had a look at your change though and taking the aggregate lists would definitely cover both scenarios.  Thanks for the quick fix!

**Comment by fabiocarvalho777** [comment]
Maybe it varies from IDE? I was using IntelliJ. Thank you too!!
