### ISSUE TITLE
Consider renaming `ResteasySpringBootConfig` to `RestEasyAutoConfiguration`

### ISSUE THREAD

**Issue by snicoll** [paypal/resteasy-spring-boot#64]
Auto-configuration are easy to find because they end with `AutoConfiguration`. This is in no way a requirement but that makes things more consistent in the auto-configuration report.

Also, since the official name of the project is `RESTEasy`,  I'd argue classes that are prefixed that way should be named `RestEasy` and not `Resteasy`.

**Comment by fabiocarvalho777** [comment]
Done, thanks for reporting it.

**Comment by fabiocarvalho777** [comment]
I had problems when trying to rename the other classes to use RestEasy prefix instead of Resteasy (git wouldn't notice any different and would not mark them as renamed), so I left that as is, but I did rename `ResteasySpringBootConfig` to `RestEasyAutoConfiguration`.
