### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by jmc420** [paypal/resteasy-spring-boot#79]
I have been trying to put together a simple spring resteasy application using the reseteasy-spring-boot project.

Everything compiles and when I run the webapp in Tomcat, the logs look as though everything is configured correctly:

16:34:45.462 [localhost-startStop-1] INFO org.jboss.resteasy.resteasy_jaxrs.i18n - RESTEASY002225: Deploying javax.ws.rs.core.Application: class org.jamescowan.example.arangodb.rest.JaxrsApplication
16:34:45.463 [localhost-startStop-1] INFO org.jboss.resteasy.resteasy_jaxrs.i18n - RESTEASY002220: Adding singleton resource org.jamescowan.example.arangodb.rest.HelloService from Application class org.jamescowan.example.arangodb.rest.JaxrsApplication

However when I go to a browser and enter http://localhost:8080/arangodb/services/hello, I get a 404.
The JavarsApplication has an @ApplicationPath("/arangodb/") and HelloService looks like this:

@Path("/services")
public class HelloService {
    @GET
    @Path("/hello")
    public String hello() {
       return "Hello";
   }
}

I would have thought that localhost:8080/arangodb/services/hello is the correct path but it does not work.

Any ideas what the problem is? Is there anyway to get resteasy to log more information on what rest endpoints it has found?

The code is here:

https://github.com/jmc420/java_examples/tree/master/arangodb

James

**Comment by fabiocarvalho777** [comment]
Hi,

Try removing [all these lines](https://github.com/jmc420/java_examples/blob/master/arangodb/src/main/java/org/jamescowan/example/arangodb/rest/JaxrsApplication.java#L14-L23), and annotate [this class](https://github.com/jmc420/java_examples/blob/master/arangodb/src/main/java/org/jamescowan/example/arangodb/rest/HelloService.java#L7) as '@Component', making it a Spring bean.

Also take a look at [this sample application](https://github.com/paypal/resteasy-spring-boot/tree/master/sample-app), [and read this](https://github.com/paypal/resteasy-spring-boot#registering-jax-rs-resources-and-providers) for further details.

**Comment by jmc420** [comment]
Thanks. I added the SpringBootServletInitializer and followed the guidelines for running it as a war file here: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-traditional-deployment.html

The actuator endpoints now work but the RestEasy endpoints still do not work.

The HelloService has a Path of "/service" and the hello method has a path of "/hello" and JaxRSApplication has @ApplicationPath("/spring-boot-arangodb/"). The url http://localhost:8080/spring-boot-arangodb/service/hello just returns with a 404.

 https://github.com/jmc420/java_examples/blob/master/spring-boot-arangodb/src/main/java/org/jamescowan/example/arangodb/rest/HelloService.java

**Comment by fabiocarvalho777** [comment]
Hi. I tested your application, converted it back to executable jar, and it worked fine for me. See the PR I sent to you.

**Comment by jmc420** [comment]
Thanks very much for doing this. I will let you know if I find a way to make it work as a war file in an external Tomcat.
