### ISSUE TITLE
Don't skip all applications if one has no path

### ISSUE THREAD

**Issue by koscejev** [paypal/resteasy-spring-boot#8]
See code in `ResteasyEmbeddedServletInitializer`. It seems that that `return` was supposed to be a `continue`. :)

```
		for (Class<? extends Application> applicationClass : applications) {
			ApplicationPath path = applicationClass.getAnnotation(ApplicationPath.class);
			if (path == null) {
				return;
			}

			GenericBeanDefinition applicationServletBean = createApplicationServlet(applicationClass, path.value());
			registry.registerBeanDefinition(applicationClass.getName(), applicationServletBean);
		}
```

**Comment by fabiocarvalho777** [comment]
Thanks a lot for reporting this bug! You are right, I meant to say "continue" there, but maybe because I didn't have breakfast that morning I said "return" instead. I have just fixed it ;-)

ps.: we will release this fix, and others, very soon via version 2.0.0
