### ISSUE TITLE
resteasy-ContainerRequestFilter-didnt-work-in-springboot

### ISSUE THREAD

**Issue by counterFish** [paypal/resteasy-spring-boot#82]
I create RequestFilte class implements ContainerRequestFilter, hoping to logging something. However , any method never go into it. I added @Provider & @Prematching . Can you help me?

**Comment by miguelsauza** [comment]
I implemented the same interface as a Provider (pre-matching) like this:

`@Provider
@PreMatching
@Component
public class ContainerRequestFilterImpl implements ContainerRequestFilter { /** overriden methods */ }`

If your spring-boot-app does no scan the package where the class is, check your scanning config. maybe you want to create this implementation as a Bean, so remove Component annotation and create the instance in config class.

**Comment by counterFish** [comment]
Did your springboot app work? What is your config class like? Can you post all related resource here?

**Comment by fabiocarvalho777** [comment]
Hello @counterFish ,

I have added a ContainerResponseFilter test case to help you out.
[Look at this commit](https://github.com/paypal/resteasy-spring-boot/commit/7d99a7ec053978b4f2bc22885b067dff8685b67a). Everything works as designed by the way.

@miguelsauza thanks for helping as well.

Regards,
Fabio Carvalho.

**Comment by counterFish** [comment]
I start a new project and it worked. However when intergrated with my existing one , it didn't work. Before , request with param like 'source_id' (using @JsonProperty("source_id") for sourceId) can work and console and log file can print 'Unrecognized field exception' . After,even just adding pom dependency, @JsonProperty can't work , request param must be sourceId, at the same time, 'Unrecognized field exception' log can only show in response,  console and log file have nothing, let alone the log I print in filter never showed off

**Comment by counterFish** [comment]
Besides, your ContainerResponseFilter can work, not ContainerRequestFilter

**Comment by counterFish** [comment]
@fabiocarvalho777

**Comment by counterFish** [comment]
what i did:
0.add pom dependency
1.@Component@Provider@PreMatching
public class RequestFilter implements ContainerResponseFilter,ContainerRequestFilter
2.@Component@ApplicationPath("/")
public class JaxrsApplication extends Application
3.SpringBootApp extends SpringBootServletInitializer
4.resteasy.jaxrs.app.registration=property
resteasy.jaxrs.app.classes=myJaxrsApplication
Did I missed something 
@fabiocarvalho777
